# Generated by Django 3.2 on 2023-06-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230620_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
