# Generated by Django 3.2 on 2023-06-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
