# Generated by Django 3.2 on 2023-06-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230621_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
