# Generated by Django 3.2 on 2023-06-21 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_freelancer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=30, unique=True),
        ),
    ]
