# Generated by Django 3.2 on 2023-06-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_freelancer_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='email',
        ),
    ]
