# Generated by Django 3.2 on 2023-06-21 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_freelancer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=uuid.uuid4, max_length=30, unique=True)),
                ('identifier', models.CharField(default=uuid.uuid4, max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_freelancer',
            new_name='is_student',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to=settings.AUTH_USER_MODEL),
        ),
    ]
