# Generated by Django 3.2 on 2023-06-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20230621_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identifier',
        ),
    ]
