# Generated by Django 3.2 on 2023-06-21 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20230621_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=30, unique=True),
        ),
    ]
