# Generated by Django 3.2 on 2023-06-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
