# Generated by Django 3.2 on 2023-06-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_identifier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_client',
            new_name='is_company',
        ),
    ]
