# Generated by Django 3.2 on 2023-06-21 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20230621_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='ceo_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='skills',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='identifier',
            field=models.CharField(default=uuid.uuid4, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=30, unique=True),
        ),
    ]
