# Generated by Django 3.2 on 2023-06-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20230621_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ceo_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
