# Generated by Django 3.2 on 2023-06-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_company_image'),
        ('comment', '0003_alter_like_likecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likecompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='account.student'),
        ),
    ]
